### ISSUE TITLE
Support for CUDA 10.0

### ISSUE THREAD

**Issue by cwbeitel** [GoogleCloudPlatform/container-engine-accelerators#106]
Looks like CUDA 10.0 requires driver version >= 410.48 and it appears the max supported by the current driver installer is 9.2 given it installs version 396.26 

```bash
root@launchtest-j0227-1834-778f-master-0:~# cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  396.26  Mon Apr 30 18:01:39 PDT 2018
GCC version:  gcc version 4.9.x 20150123 (prerelease) (4.9.2_cos_gg_4.9.2-r193-ac6128e0a17a52f011797f33ac3e7d6273a9368d_4.9.2-r193)
```

and Table 1 [here](https://docs.nvidia.com/deploy/cuda-compatibility/index.html). Corroborated by [GPUs on GKE docs](https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#cuda) mentioning max supported CUDA is 9.*.

Is it feasible to update the driver version to 410.48 in order to support all current CUDA versions?

This is especially relevant because tensorflow-gpu releases are now compiled for CUDA 10.0 by default iiuc, i.e. the version that is installed upon `pip install tensorflow-gpu==1.13.1` expects CUDA 10.0 and requires rebuilding from source otherwise.

/cc https://github.com/kubeflow/kubeflow/issues/2573 @jlewi

**Comment by vishh** [comment]
CUDA 10 is supported, but the docs are yet to be updated - Apologies! Try using GKE v1.11.5+.

**Comment by cwbeitel** [comment]
Ah interesting, thank you @vishh
