### ISSUE TITLE
init container error on v1.15.4-gke.15

### ISSUE THREAD

**Issue by itayvallach** [GoogleCloudPlatform/container-engine-accelerators#127]
nvidia-driver-installer init container fails.
OS: COS
uses latest config:
https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml

When using above code from September 22, 2019, everything works fine, thus error is related to the latest 2 commits from the last month. Logs:

+ COS_DOWNLOAD_GCS=https://storage.googleapis.com/cos-tools
+ COS_KERNEL_SRC_GIT=https://chromium.googlesource.com/chromiumos/third_party/kernel
+ COS_KERNEL_SRC_ARCHIVE=kernel-src.tar.gz
+ TOOLCHAIN_URL_FILENAME=toolchain_url
+ TOOLCHAIN_ARCHIVE=toolchain.tar.xz
+ TOOLCHAIN_ENV_FILENAME=toolchain_env
+ TOOLCHAIN_PKG_DIR=/build/cos-tools
+ CHROMIUMOS_SDK_GCS=https://storage.googleapis.com/chromiumos-sdk
+ ROOT_OS_RELEASE=/root/etc/os-release
+ KERNEL_SRC_DIR=/build/usr/src/linux
+ NVIDIA_DRIVER_VERSION=418.67
+ NVIDIA_DRIVER_MD5SUM=
+ NVIDIA_INSTALL_DIR_HOST=/home/kubernetes/bin/nvidia
+ NVIDIA_INSTALL_DIR_CONTAINER=/usr/local/nvidia
+ ROOT_MOUNT_DIR=/root
+ CACHE_FILE=/usr/local/nvidia/.cache
+ LOCK_FILE=/root/tmp/cos_gpu_installer_lock
+ LOCK_FILE_FD=20
+ set +x
[INFO    2019-10-29 10:11:43 UTC] PRELOAD: false
[INFO    2019-10-29 10:11:43 UTC] Checking if this is the only cos-gpu-installer that is running.
[INFO    2019-10-29 10:11:43 UTC] Running on COS build id 12371.57.0
[INFO    2019-10-29 10:11:43 UTC] Checking if third party kernel modules can be installed
[INFO    2019-10-29 10:11:43 UTC] Checking cached version
[INFO    2019-10-29 10:11:43 UTC] Cache file /usr/local/nvidia/.cache not found.
[INFO    2019-10-29 10:11:43 UTC] Did not find cached version, building the drivers...
[INFO    2019-10-29 10:11:43 UTC] Downloading GPU installer ... 
/usr/local/nvidia /
[INFO    2019-10-29 10:11:43 UTC] Downloading from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/418.67/NVIDIA-Linux-x86_64-418.67.run
/
ls: cannot access '/build/usr/src/linux': No such file or directory
[INFO    2019-10-29 10:11:45 UTC] Kernel sources not found locally, downloading
[INFO    2019-10-29 10:11:45 UTC] Kernel source archive download URL: https://storage.googleapis.com/cos-tools/12371.57.0/kernel-src.tar.gz
/build/usr/src/linux /
/

real    0m1.351s
user    0m0.196s
sys     0m0.409s
/build/usr/src/linux /
/
[INFO    2019-10-29 10:11:53 UTC] Setting up compilation environment
[INFO    2019-10-29 10:11:53 UTC] Obtaining toolchain_env file from https://storage.googleapis.com/cos-tools/12371.57.0/toolchain_env

real    0m0.027s
user    0m0.015s
sys     0m0.004s
[INFO    2019-10-29 10:11:53 UTC] /build/cos-tools: bin
lib
toolchain.tar.xz
usr
[INFO    2019-10-29 10:11:53 UTC] Found existing toolchain package. Skipping download and installation
[INFO    2019-10-29 10:11:53 UTC] Configuring environment variables for cross-compilation
[INFO    2019-10-29 10:11:53 UTC] Configuring installation directories
/usr/local/nvidia /
[INFO    2019-10-29 10:11:53 UTC] Updating container's ld cache
/
[INFO    2019-10-29 10:11:53 UTC] Configuring kernel sources
/build/usr/src/linux /
/bin/sh: 1: x86_64-cros-linux-gnu-clang: Permission denied
  HOSTCC  scripts/basic/fixdep
/bin/sh: 1: x86_64-cros-linux-gnu-clang: Permission denied
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --olddefconfig Kconfig
./scripts/gcc-version.sh: 26: ./scripts/gcc-version.sh: x86_64-cros-linux-gnu-clang: Permission denied
./scripts/gcc-version.sh: 27: ./scripts/gcc-version.sh: x86_64-cros-linux-gnu-clang: Permission denied
./scripts/gcc-version.sh: 29: ./scripts/gcc-version.sh: x86_64-cros-linux-gnu-clang: Permission denied
./scripts/gcc-version.sh: 26: ./scripts/gcc-version.sh: x86_64-cros-linux-gnu-clang: Permission denied
./scripts/gcc-version.sh: 27: ./scripts/gcc-version.sh: x86_64-cros-linux-gnu-clang: Permission denied
./scripts/gcc-version.sh: 29: ./scripts/gcc-version.sh: x86_64-cros-linux-gnu-clang: Permission denied
init/Kconfig:17: syntax error
init/Kconfig:16: invalid option
./scripts/clang-version.sh: 15: ./scripts/clang-version.sh: x86_64-cros-linux-gnu-clang: Permission denied
./scripts/gcc-plugin.sh: 11: ./scripts/gcc-plugin.sh: x86_64-cros-linux-gnu-clang: Permission denied
make[1]: *** [olddefconfig] Error 1
scripts/kconfig/Makefile:69: recipe for target 'olddefconfig' failed
make: *** [olddefconfig] Error 2
Makefile:529: recipe for target 'olddefconfig' failed

**Comment by chardch** [comment]
Hi @itayvallach is this still occurring? This seems like it's due to the same issue here: GoogleCloudPlatform/cos-gpu-installer#45 and should be resolved with this revert: https://github.com/GoogleCloudPlatform/container-engine-accelerators/pull/126

**Comment by itayvallach** [comment]
Seems it is indeed resolved now.
