### ISSUE TITLE
How to build the cmd/nvidia_gpu/ to a binary exec file

### ISSUE THREAD

**Issue by tianshapjq** [GoogleCloudPlatform/container-engine-accelerators#53]
I have cloned this project and go get the related projects, such as golang.org/x/net/context and google.golang.org/grpc. But I got the error message as below when running "go build":

./nvidia_gpu.go:113:43: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"k8s.io/kubernetes/vendor/google.golang.org/grpc".ClientConn in argument to deviceplugin.NewRegistrationClient

anything else do I need to setup for the GOPATH?

**Comment by tianshapjq** [comment]
@mindprince would you please give me some advise?

**Comment by mindprince** [comment]
You shouldn't need to `go get` anything. The vendor directory has everything that's needed.

When I run into GOPATH issues, I prefer to just do this inside a docker container. Something like:
```
# Create build container.
docker run -ti -v ~/go/src/github.com/GoogleCloudPlatform/container-engine-accelerators:/go/src/github.com/GoogleCloudPlatform/container-engine-accelerators golang:1.9.2-stretch bash

# Inside the container
cd /go/src/github.com/GoogleCloudPlatform/container-engine-accelerators
make build
```

**Comment by tianshapjq** [comment]
@mindprince you are right, I make a mistake for cloning cmd/nvidia_gpu dir and building it directly. Thanks!
