### ISSUE TITLE
Consider adding cuda libraries to path for container mounts

### ISSUE THREAD

**Issue by cmluciano** [GoogleCloudPlatform/container-engine-accelerators#60]
It would be helpful if we can copy or mount in other paths that CUDA (and by extension TensorFlow) need to run CUDA jobs. 

Tensorflow will look for libraries like libcupti within `LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64`.

I'm not sure how GKE is solving the CUDA availability. I think it might be sufficient to manually copy the libraries from `/usr/local/cuda/extras/CUPTI/lib64` that contains 
`libcupti.so  libcupti.so.9.0  libcupti.so.9.0.176`. 

Few options:

- Simply document the need to copy libs to the correct path
- Collect the necessary CUDA libraries at nvidia-installer runtime and move copy them at install-time (this assumes you installed CUDA on the host)
- Add a new flag that can be used to mount CUDA libraries from the desired host-path  

I can submit a PR for this if anyone finds it useful.

**Comment by flx42** [comment]
CUPTI is part of the CUDA toolkit, it should be shipped inside the container.
But I dropped the ball for the non-devel TF Dockerfile, and forgot to include it in my last patch:
https://github.com/tensorflow/tensorflow/issues/17431

**Comment by cmluciano** [comment]
Ah! Does that mean it should not be required for installation on the host itself?

**Comment by flx42** [comment]
Correct.

**Comment by cmluciano** [comment]
Ok. Before I close this, is it possible to mount the files from the package installed on the host or would that be a nightmare for potential CUDA compatibility problems?

cc @mindprince @jiayingz Not sure what you are doing in GKE

**Comment by flx42** [comment]
> Before I close this, is it possible to mount the files from the package installed on the host or would that be a nightmare for potential CUDA compatibility problems?

In the case of CUPTI, I honestly don't really know. But it's safer to match the CUDA version inside your container.

**Comment by mindprince** [comment]
On the host, we have the bare minimum stuff (kernel modules and libraries that need to match the host kernel version), for everything else, we recommend users to use docker images based off of nvidia/cuda images: https://cloud.google.com/kubernetes-engine/docs/concepts/gpus#configuring_pods_to_consume_gpus

**Comment by cmluciano** [comment]
Cool thanks all!
