### ISSUE TITLE
nvidia-gpu daemonset using hostNetworking

### ISSUE THREAD

**Issue by kodieGlosser** [GoogleCloudPlatform/container-engine-accelerators#64]
Copied from https://github.com/kubernetes/kubernetes/issues/62357, probably a better place to open here.

Host Networking is enabled for the nvidia-gpu daemonset. Trying to understand the purpose of using it.
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml#L30

Disabling hostNetworking seemed to work and GPU workloads are able to be scheduled to the cluster.

*How to reproduce it (as minimally and precisely as possible):*
Remove this line and apply the daemonset to a GPU enabled cluster.
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml#L30

*Anything else we need to know?:*
I would like to understand the purpose for using hostNetworking for the nvidia-gpu daemonset. It appears nvidia implementation does not use it either: https://github.com/NVIDIA/k8s-device-plugin/blob/v1.10/nvidia-device-plugin.yml

**Comment by cmluciano** [comment]
@mindprince is this for the kubelet and plugin to communicate over a socket?

**Comment by flx42** [comment]
@cmluciano for that you just need to have permissions that match the kubelet socket file. `root` in this case.

**Comment by flx42** [comment]
You can even run with `network=none`:
https://github.com/NVIDIA/k8s-device-plugin#run-locally
But K8s doesn't offer this feature AFAIK.

**Comment by kodieGlosser** [comment]
Thanks for the response @flx42 . Where exactly can I see the permissions on my kubelet socket file?

When you say 
> `root` in this case

are you talking about your specific case? 

If I was able to schedule a GPU workload with the device-plugin running **without** hostNetwork, would that indicate that the kubelet and the plugin can communicate over the socket and the permissions on my kubelet socket file are good?

**Comment by kodieGlosser** [comment]
Actually I see what you are saying here:

```ls -lth
total 4.0K
-rw-r--r-- 1 root root 1.1K Apr 11 11:31 kubelet_internal_checkpoint
srwxr-xr-x 1 root root    0 Apr 11 11:31 nvidiaGPU-1523464309.sock
srwxr-xr-x 1 root root    0 Apr 11 11:26 kubelet.sock```

**Comment by kodieGlosser** [comment]
and the logs look to be the same without hostNetwork:

```kubectl logs -n kube-system nvidia-gpu-device-plugin-ntq2t
I0411 16:31:49.206754   14059 nvidia_gpu.go:40] device-plugin started
I0411 16:31:49.211600   14059 manager.go:79] Found Nvidia GPU "nvidia0"
I0411 16:31:49.212011   14059 manager.go:79] Found Nvidia GPU "nvidia1"
I0411 16:31:49.212073   14059 manager.go:130] will use alpha API
I0411 16:31:49.212086   14059 manager.go:144] starting device-plugin server at: /device-plugin/nvidiaGPU-1523464309.sock
I0411 16:31:49.301775   14059 manager.go:173] device-plugin server started serving
I0411 16:31:49.902012   14059 manager.go:185] device-plugin registered with the kubelet
I0411 16:31:50.114880   14059 alpha_plugin.go:34] device-plugin: ListAndWatch start
I0411 16:31:50.204030   14059 alpha_plugin.go:42] ListAndWatch: send devices &ListAndWatchResponse{Devices:[&Device{ID:nvidia0,Health:Healthy,} &Device{ID:nvidia1,Health:Healthy,}],}```

**Comment by flx42** [comment]
Yeah, you don't control the ownership of this file. But it does require the device plugin container to run as `root`.

Additional permissions/capabilities will depend on the particular device plugin implementation. For our own implementation, we need pretty much nothing.

**Comment by kodieGlosser** [comment]
To run as root we should only need 

```        securityContext:
          privileged: true```

I'm wondering if we even need hostPID.

**Comment by flx42** [comment]
No, quite the opposite. `privileged` will remove the LSM confinement (apparmor, seccomp) and give you extra capabilities (`CAP_SYS_ADMIN`).

**Comment by kodieGlosser** [comment]
Ok. Then what is need to run this device plugin as root?

**Comment by flx42** [comment]
That's the default for a container. You have to explicitly state you want a different UID with `runAsUser`

**Comment by mindprince** [comment]
Hi,

I think `hostNetwork` and `hostPID` in the manifest are artifacts of copy-paste. I will send a PR to remove them.

**Comment by kodieGlosser** [comment]
ok thanks for the info @flx42. Appreciate it!

**Comment by mindprince** [comment]
Closing. Fixed in https://github.com/kubernetes/kubernetes/pull/62418

**Comment by reverson** [comment]
@mindprince This is still referenced in the file linked to from here: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#nvidia-gpu-device-plugin-used-by-gke-gce

**Comment by mindprince** [comment]
It was fixed on kubernetes master branch and was not backported to earlier branches. Once 1.11 is released, we will update the docs to point to the URL from that branch. (It's an addon on GCE/GKE, so once your GKE/GCE cluster moves to 1.11 master, it would stop using hostnetwork/hostPID for this device plugin)
