### ISSUE TITLE
when asked for 1 gpu device, gpu is available as /dev/nvidia1 not /dev/nvidia0

### ISSUE THREAD

**Issue by gurvindersingh** [GoogleCloudPlatform/container-engine-accelerators#72]
I have a server with two GPU in it. So when I asked for 1 gpu in the pod and there is no other gpu pod running on server, I get correct index device exposed into pod as `/dev/nvidia0`. But when I have one gpu pod already running on that server and I schedule another pod with 1 gpu in requests, it get GPU device exposed but its index is not `/dev/nvidia0` but `/dev/nvidia1` this causes some issue with the underlying applications. 

I am running k8s 1.10 and device plugin image with hash `0842734032018be107fa2490c98156992911e3e1f2a21e059ff0105b07dd8e9e`. Let me know if you need any more info but to me the issue might be in [this code](https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/pkg/gpu/nvidia/beta_plugin.go#L71)

**Comment by mindprince** [comment]
This was discussed before. The conclusion was that we wanted to make the device available at the same minor number as it has on the host. However, I can't find the discussion thread.

cc @vishh

**Comment by vishh** [comment]
This is an Nvidia restriction and there is no way around it. IIUC, GPU apps are expected to rely on higher level APIs like CUDA which are supposed to hide issues like this one. @gurvindersingh can you explain why device naming is breaking your app?

**Comment by gurvindersingh** [comment]
As the application was expecting `/dev/nvidia0`. Its an simple application written internally. We can look into updating with cuda mechanism you are referring. So it seems there is no way around currently then.
