### ISSUE TITLE
device plugin to emit metrics?

### ISSUE THREAD

**Issue by lsjostro** [GoogleCloudPlatform/container-engine-accelerators#78]
Just a question, is the device plugin responsible for emitting metrics for say allocation or is this handled by kubelet? cAdvisor had acceleration metrics previously which now is deprecated in k8s 1.11.

kubelet currently only has `kubelet_device_plugin_alloc_latency_microseconds` metric what I can see. 

Would you be willing to accept a PR for exposing a metrics endpoint?

**Comment by mindprince** [comment]
cAdvisor will continue to be the source of accelerator metrics till a replacement is ready. Currently, it exposes three metrics `duty_cycle`, `memory_used` and `memory_total`.

Not sure what you exactly mean by allocation metrics, but currently heapster (which is also deprecated) exposes how many GPUs a pod has requested. The other place such metrics are exposed is kube-state-metrics.

@dashpole is working on a proposal that will give device plugins enough information to properly expose pod and container level metrics.

What exact metrics do you want to expose?

**Comment by lsjostro** [comment]
Alright, cool. I would like to have metrics on how many gpus are allocated and in use within a node pool for instance. You had that previously from kube-state-metrics when feature flag acceleration was enabled in kubelet. `kube_node_status_allocatable_nvidia_gpu_cards` Now when that is deprecated in 1.11 I just wounder how I can get that back?

**Comment by lsjostro** [comment]
Thanks! I’ll look into that! Cheers!
