### ISSUE TITLE
ubuntu driver install container crashed when nvidia.ko is already loaded. 

### ISSUE THREAD

**Issue by AtzeDeVries** [GoogleCloudPlatform/container-engine-accelerators#90]
In  https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/nvidia-driver-installer/ubuntu/entrypoint.sh there is a if statement to check if nvidia kernel module is loaded. It looks like this (line 139)
```
  if ! lsmod | grep -q -w 'nvidia'; then
    insmod "${NVIDIA_INSTALL_DIR_CONTAINER}/drivers/nvidia.ko"
  fi
  if ! lsmod | grep -q -w 'nvidia_uvm'; then
    insmod "${NVIDIA_INSTALL_DIR_CONTAINER}/drivers/nvidia-uvm.ko"
  fi
```
In `entrypoint.sh` at line 17 `set -o pipifail` is defined. This causes the check at line 139 to be always true and always tries to load the `nvidia.ko` even if it is already loaded. This causes the container to crash. 

A solution could be to remove `set -o pipefail`. I can do a PR if you want.

**Comment by mindprince** [comment]
I don't understand. How does `pipefail` has anything to do with this? The first command in the pipeline always returns exit code 0. So, `pipefail` doesn't have any effect on this pipeline.

If `nvidia.ko` is already loaded then `lsmod | grep -q -w 'nvidia'` returns exit code 0. `if !` makes sure the if condition is not executed.

This restart handling was added recently in #75. Maybe you are running a version that's based on a version earlier than #76?

**Comment by AtzeDeVries** [comment]
if you enter this in a shell
```
set -o pipefail
if ! lsmod | grep -q -w 'nvidia' ; then echo found ; fi #or any other module you have loaded. 
```
if you set `set +o pipefail` it works as expected. I though it might be because if you run
`! lsmod` in a shell it returns exit-code 1

**Comment by AtzeDeVries** [comment]
and i've double checked and i'm using `eea7309dc4fa4a5c9d716157e74b90826e0a853aa26c7219db4710ddcd1ad8bc` version of `ubuntu-nvidia-driver-installer` which is the same as in #76

**Comment by kaoet** [comment]
I also encountered this issue. And I have found the root cause.

According to [manpage of grep](https://linux.die.net/man/1/grep), in quiet mode, `grep` exits immediately when the first match is found.
```
 -q, --quiet, --silent
              Quiet; do not write anything to standard output.  Exit immediately with zero status if any match is found, even if
              an error was detected.  Also see the -s or --no-messages option.
```

This causes `lsmod` fail to write to its stdout, and `lsmod` exits with non-zero.

A simple fix is to remove the `-q` option from `grep`.

**Comment by mindprince** [comment]
Thank you! Sorry it took a long time to get to this.

**Comment by mindprince** [comment]
BTW, GKE now supports NVIDIA GPUs on Ubuntu image officially. Check out the docs for a faster installation experience: https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#installing_drivers
